# Dockerfile.modeling
FROM python:3.9

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY modeling_server1.py .

CMD ["uvicorn", "modeling_server1:app", "--host", "0.0.0.0", "--port", "8000"]